# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6605a969f540faa48ea81f37ebed8836ade4c87ec63dbd3eb50f71d0559ef2039fa264fa5c345a55b95e97cf23820ef41de26a52b4e1e6396377344454679870

test:
  secret_key_base: 43ce1f63b5a9a9970b6f6f98ec9b72f8c24004b8b5cc28dd59dc9e9fe008d3b40119b391b8112e26f5133889c0b4a90d52bfaca71d48ef3a59a78d71b0f74ddd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
